// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_Eh9ZPXkMjBVPEEYKX4vM4fUZAt0NQhE',
    appId: '1:100226634982:android:80072cc2de21a0fcb29727',
    messagingSenderId: '100226634982',
    projectId: 'discount-link-532cc',
    storageBucket: 'discount-link-532cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg_CZSISfA1Gm24atoWIMGsq3uGBPq0ac',
    appId: '1:100226634982:ios:c7f47186837c7831b29727',
    messagingSenderId: '100226634982',
    projectId: 'discount-link-532cc',
    storageBucket: 'discount-link-532cc.firebasestorage.app',
    androidClientId:
        '100226634982-aogpnipk2vhl1888lbdaebpuq2f27dr6.apps.googleusercontent.com',
    iosClientId:
        '100226634982-g82niiqvs9r13u134gsitrkm4ah6fc2k.apps.googleusercontent.com',
    iosBundleId: 'net.vigourtech.dl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg_CZSISfA1Gm24atoWIMGsq3uGBPq0ac',
    appId: '1:100226634982:ios:c7f47186837c7831b29727',
    messagingSenderId: '100226634982',
    projectId: 'discount-link-532cc',
    storageBucket: 'discount-link-532cc.firebasestorage.app',
    androidClientId:
        '100226634982-aogpnipk2vhl1888lbdaebpuq2f27dr6.apps.googleusercontent.com',
    iosClientId:
        '100226634982-g82niiqvs9r13u134gsitrkm4ah6fc2k.apps.googleusercontent.com',
    iosBundleId: 'net.vigourtech.dl',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyjb4_MIz70pv3OgD2f5fdL9DGIwAmewU',
    appId: '1:100226634982:web:aac96ac97dd2b8a3b29727',
    messagingSenderId: '100226634982',
    projectId: 'discount-link-532cc',
    authDomain: 'discount-link-532cc.firebaseapp.com',
    storageBucket: 'discount-link-532cc.firebasestorage.app',
    measurementId: 'G-E6D0MCJB1Q',
  );
}
